/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;
import clases.Contacto;
import javax.swing.JOptionPane;

/**
 *
 * @author dell-pc
 */
public class VistaEditar extends javax.swing.JFrame {

    /**
     * Creates new form VistaModificar
     */
    
    Contacto agenda;
    Index inicio;
    
    public VistaEditar(Contacto agenda, Index inicio) {
        
        initComponents();
        
        // Asignar los parámetros recibidos a las variables de instancia
        this.agenda = agenda;
        this.inicio = inicio;
        
        inicio.setVisible(false);
        
        // Llenar los campos de texto con la información del contacto existente
        areaName.setText(agenda.getNombre());
        areaTelefono.setText(agenda.getTelefono());
        areaEmail.setText(agenda.getEmail());
        areaCiudad.setText(agenda.getCiudad());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEmail = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        areaCiudad = new javax.swing.JTextField();
        areaName = new javax.swing.JTextField();
        areaTelefono = new javax.swing.JTextField();
        areaEmail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(157, 158, 160));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(0, 0, 0));
        txtEmail.setText("Email:");

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.setText("Nombre:");

        txtCiudad.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtCiudad.setForeground(new java.awt.Color(0, 0, 0));
        txtCiudad.setText("Ciudad:");

        txtTelefono.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(0, 0, 0));
        txtTelefono.setText("Teléfono:");

        btnGuardar.setBackground(new java.awt.Color(121, 173, 220));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        areaCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaCiudadActionPerformed(evt);
            }
        });

        areaName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaNameActionPerformed(evt);
            }
        });

        areaTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaTelefonoActionPerformed(evt);
            }
        });

        areaEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(areaCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(areaTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(areaEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(areaName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(areaName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(areaTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(areaEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(areaCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Método para establecer una referencia a una instancia de la clase Index
    private Index index;
    
    public void setIndexReference(Index index) {
        this.index = index;
    }
    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
    
        // Obtener la información de los campos de texto
        String nombre = areaName.getText();
        String telefono = areaTelefono.getText();
        String email = areaEmail.getText();
        String ciudad = areaCiudad.getText();

        // Verificar que los campos de textos no estén vacíos
        if (!nombre.isEmpty()) {
            if (!telefono.isEmpty()) {
                if (!email.isEmpty()) {
                    if (!ciudad.isEmpty()) {
                        
                        // Actualizar el contacto existente con la nueva información
                        agenda.setNombre(nombre);
                        agenda.setTelefono(telefono);
                        agenda.setEmail(email);
                        agenda.setCiudad(ciudad);
                        
                    } else {
                        JOptionPane.showMessageDialog(null, "El campo de ciudad se encuentra vacío");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El campo de email se encuentra vacío");
                }
            } else {
                JOptionPane.showMessageDialog(null, "El campo de telefono se encuentra vacío");
            }
        } else {
            JOptionPane.showMessageDialog(null, "El campo de nombre se encuentra vacío");
        }

        // Volver a la ventana principal y mostrar los cambios
        inicio.setVisible(true);
        index.mostrarCambiosEnContacto(agenda);
        this.dispose();  // Cerrar la ventana de edición
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void areaCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areaCiudadActionPerformed

    private void areaNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areaNameActionPerformed

    private void areaTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areaTelefonoActionPerformed

    private void areaEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areaEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField areaCiudad;
    private javax.swing.JTextField areaEmail;
    private javax.swing.JTextField areaName;
    private javax.swing.JTextField areaTelefono;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel txtCiudad;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtTelefono;
    // End of variables declaration//GEN-END:variables
}
