nivel1 = {
    "agua": "../niveles/nivel1_csv/nivel1_agua.csv",
    "arbol1": "../niveles/nivel1_csv/nivel1_arbol1.csv",
    "arbol2": "../niveles/nivel1_csv/nivel1_arbol2.csv",
    "arbusto1": "../niveles/nivel1_csv/nivel1_arbusto1.csv",
    "arbusto2": "../niveles/nivel1_csv/nivel1_arbusto2.csv",
    "arbusto3": "../niveles/nivel1_csv/nivel1_arbusto3.csv",
    "arbusto4": "../niveles/nivel1_csv/nivel1_arbusto4.csv",
    "cajas": "../niveles/nivel1_csv/nivel1_cajas.csv",
    "cartel1": "../niveles/nivel1_csv/nivel1_cartel1.csv",
    "cartel2": "../niveles/nivel1_csv/nivel1_cartel2.csv",
    "choque_enemigo": "../niveles/nivel1_csv/nivel1_choque_enemigo.csv",
    "choque_personaje": "../niveles/nivel1_csv/nivel1_choque_personaje.csv",
    "enemigo": "../niveles/nivel1_csv/nivel1_enemigo.csv",
    "monedas": "../niveles/nivel1_csv/nivel1_monedas.csv",
    "mushroom_dec": "../niveles/nivel1_csv/nivel1_mushroom_dec.csv",
    "mushroom_salto": "../niveles/nivel1_csv/nivel1_mushroom_salto.csv",
    "olas": "../niveles/nivel1_csv/nivel1_olas.csv",
    "personaje": "../niveles/nivel1_csv/nivel1_personaje.csv",
    "rocas": "../niveles/nivel1_csv/nivel1_rocas.csv",
    "terreno": "../niveles/nivel1_csv/nivel1_terreno.csv",
    "troncos": "../niveles/nivel1_csv/nivel1_troncos.csv",
    "posicion": (140, 352),
    "desbloquea": 1,
    "grafico": "../graficos/menu/nivel1.png"
}

nivel2 = {
    "agua": "../niveles/nivel2_csv/nivel2_agua.csv",
    "arbol1": "../niveles/nivel2_csv/nivel2_arbol1.csv",
    "arbol2": "../niveles/nivel2_csv/nivel2_arbol2.csv",
    "arbusto1": "../niveles/nivel2_csv/nivel2_arbusto1.csv",
    "arbusto2": "../niveles/nivel2_csv/nivel2_arbusto2.csv",
    "arbusto3": "../niveles/nivel2_csv/nivel2_arbusto3.csv",
    "arbusto4": "../niveles/nivel2_csv/nivel2_arbusto4.csv",
    "cajas": "../niveles/nivel2_csv/nivel2_cajas.csv",
    "cartel1": "../niveles/nivel2_csv/nivel2_cartel1.csv",
    "cartel2": "../niveles/nivel2_csv/nivel2_cartel2.csv",
    "choque_enemigo": "../niveles/nivel2_csv/nivel2_choque_enemigo.csv",
    "choque_personaje": "../niveles/nivel2_csv/nivel2_choque_personaje.csv",
    "enemigo": "../niveles/nivel2_csv/nivel2_enemigo.csv",
    "monedas": "../niveles/nivel2_csv/nivel2_monedas.csv",
    "mushroom_dec": "../niveles/nivel2_csv/nivel2_mushroom_dec.csv",
    "mushroom_salto": "../niveles/nivel2_csv/nivel2_mushroom_salto.csv",
    "olas": "../niveles/nivel2_csv/nivel2_olas.csv",
    "personaje": "../niveles/nivel2_csv/nivel2_personaje.csv",
    "rocas": "../niveles/nivel2_csv/nivel2_rocas.csv",
    "terreno": "../niveles/nivel2_csv/nivel2_terreno.csv",
    "troncos": "../niveles/nivel2_csv/nivel2_troncos.csv",
    "posicion": (625, 352),
    "desbloquea": 2,
    "grafico": "../graficos/menu/nivel2.png"
}

nivel3 = {
    "agua": "../niveles/nivel2_csv/nivel2_agua.csv",
    "arbol1": "../niveles/nivel2_csv/nivel2_arbol1.csv",
    "arbol2": "../niveles/nivel2_csv/nivel2_arbol2.csv",
    "arbusto1": "../niveles/nivel2_csv/nivel2_arbusto1.csv",
    "arbusto2": "../niveles/nivel2_csv/nivel2_arbusto2.csv",
    "arbusto3": "../niveles/nivel2_csv/nivel2_arbusto3.csv",
    "arbusto4": "../niveles/nivel2_csv/nivel2_arbusto4.csv",
    "cajas": "../niveles/nivel2_csv/nivel2_cajas.csv",
    "cartel1": "../niveles/nivel2_csv/nivel2_cartel1.csv",
    "cartel2": "../niveles/nivel2_csv/nivel2_cartel2.csv",
    "choque_enemigo": "../niveles/nivel2_csv/nivel2_choque_enemigo.csv",
    "choque_personaje": "../niveles/nivel2_csv/nivel2_choque_personaje.csv",
    "enemigo": "../niveles/nivel2_csv/nivel2_enemigo.csv",
    "monedas": "../niveles/nivel2_csv/nivel2_monedas.csv",
    "mushroom_dec": "../niveles/nivel2_csv/nivel2_mushroom_dec.csv",
    "mushroom_salto": "../niveles/nivel2_csv/nivel2_mushroom_salto.csv",
    "olas": "../niveles/nivel2_csv/nivel2_olas.csv",
    "personaje": "../niveles/nivel2_csv/nivel2_personaje.csv",
    "rocas": "../niveles/nivel2_csv/nivel2_rocas.csv",
    "terreno": "../niveles/nivel2_csv/nivel2_terreno.csv",
    "troncos": "../niveles/nivel2_csv/nivel2_troncos.csv",
    "posicion": (1140, 352),
    "desbloquea": 2,
    "grafico": "../graficos/menu/nivel3.png"
}

niveles = {
    0: nivel1,
    1: nivel2,
    2: nivel3,
}